### ISSUE TITLE
github action: http-user-agent 

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/shinytest2#280]
In https://rstudio.github.io/shinytest2/articles/use-ci.html#a-repository-with-a-single-application, the `check-app.yaml` includes:

```
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true
```

...but `http-user-agent` is not set in:

```
   strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: release}
```

...so `http-user-agent` will be set to a blank string, correct? 

Why include `http-user-agent: ${{ matrix.config.http-user-agent }}`?
