### ISSUE TITLE
CI: failing on linux os if curl is a dependency

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/shinytest2#282]
The github action yaml in the [docs on CI](https://rstudio.github.io/shinytest2/articles/use-ci.html) is shown as:

```
# Workflow derived from https://github.com/rstudio/shinytest2/tree/main/actions/test-app/example-test-app-description.yaml
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Test app w/ {renv}

jobs:
  test-app:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: release}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-renv@v2

      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          path: "."
```

...but this results in failed tests for linux, if the `curl` package is a dependency. Including `apt-get install -y libcurl4-openssl-dev` fixed the issue for me:

```
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: my_shiny_app

jobs:
  test-app:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} (${{ matrix.r }})
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        r: [4.2.1]
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - name: Install linux system dependencies
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
      - name: Checkout
        uses: actions/checkout@v2
      - name: r-lib pandoc setup
        uses: r-lib/actions/setup-pandoc@v2
      - name: r-lib setup
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: false
      - name: rlib renv setup
        uses: r-lib/actions/setup-renv@v2
      - name: Test with shinytest2
        uses: rstudio/shinytest2/actions/test-app@v1
        with:
          path: "."
```
