### ISSUE TITLE
GitHub Action: Load parent renv project when testing multiple apps via `app-dir` input

### ISSUE THREAD

**Issue by nick-youngblut** [rstudio/shinytest2#359]
I followed the example at [Using shinytest2 with continuous integration](https://rstudio.github.io/shinytest2/articles/use-ci.html), with slight modifications:

```
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: Test app with renv

jobs:
  test-app:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest, r: "4.3.1"}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true
      - uses: r-lib/actions/setup-renv@v2
      - uses: rstudio/shinytest2/actions/test-app@v1
        with:
          app-dir: |
            app
          upload-snapshots: true     
```

For the sake of GCP Cloud Run deployment, my Shiny app is located at `./app/` in the repo. 

`shinytest2` is in my renv snapshot file, and it was successfully installed in the `r-lib/actions/setup-renv@v2` step prior to `rstudio/shinytest2/actions/test-app@v1`.

My `testthat.R` file:

```
shinytest2::test_app()
```

My `setup-shinytest2.R` file:

```
# Load application support files into testing environment
shinytest2::load_app_env()
```

My `test-shinytest2.R` file:

```
library(shinytest2)

# test app initialization
test_that("App initialization is consistent", {
  app <- AppDriver$new(name = "app", height = 768, width = 1211)
  app$expect_values()
})
```
